{{- if .Values.readarr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-readarr
  labels:
    app.kubernetes.io/name: readarr
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  {{- if not .Values.readarr.autoscaling.enabled }}
  replicas: {{ .Values.readarr.replicaCount }}
  {{- end }}
  strategy:
    {{- .Values.readarr.deployment.strategy | toYaml | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: readarr
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.readarr.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: readarr
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    spec:
      {{- with .Values.readarr.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.readarr.serviceAccount.name | default (printf "%s-readarr" .Release.Name) }}
      securityContext:
        {{- toYaml .Values.readarr.podSecurityContext | nindent 8 }}
      {{- if and .Values.jellyfin.enabled .Values.jellyfin.persistence.media.enabled .Values.readarr.persistence.enabled .Values.readarr.persistence.createInitContainer }}
      initContainers:
        - name: init-directories
          image: busybox
          command: ['sh', '-c', 'mkdir -p /media/{{ .Values.readarr.persistence.path }} /media/{{ .Values.qbittorrent.persistence.path }} && chown -R 1000:1000 /media/{{ .Values.readarr.persistence.path }} /media/{{ .Values.qbittorrent.persistence.path }}']
          volumeMounts:
            - name: media
              mountPath: /media
      {{- if .Values.readarr.initContainers }}
        {{- toYaml .Values.readarr.initContainers | nindent 8 }}
      {{- end }}
      {{- end }}
      volumes:
        - name: config
          {{- if .Values.readarr.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.readarr.persistence.existingClaim | default (printf "%s-readarr" .Release.Name) }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        - name: media
          {{- if and .Values.jellyfin.enabled .Values.jellyfin.persistence.media.enabled .Values.readarr.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-jellyfin-media
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if .Values.readarr.persistence.additionalVolumes }}
          {{- .Values.readarr.persistence.additionalVolumes | toYaml | nindent 8}}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.readarr.securityContext | nindent 12 }}
          image: "{{ .Values.readarr.image.repository }}:{{ .Values.readarr.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.readarr.image.pullPolicy }}
          volumeMounts:
            - mountPath: /config
              name: config
          {{- if and .Values.jellyfin.enabled .Values.jellyfin.persistence.media.enabled .Values.readarr.persistence.enabled }}
            - mountPath: /media
              name: media
          {{- end }}
          {{- if .Values.readarr.persistence.additionalMounts }}
            {{- .Values.readarr.persistence.additionalMounts | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8787
              protocol: TCP
          env:
            {{- range $k,$v := .Values.readarr.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            failureThreshold: 12
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /ping
              port: http
            failureThreshold: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.readarr.resources | nindent 12 }}
      {{- with .Values.readarr.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.readarr.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.readarr.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}